### ISSUE TITLE
Link overflow

### ISSUE THREAD

**Issue by Telianth** [beerjs/skopje#1]
On mobile version, the static link about BeerJS Vol.2 overflows in a new line.
![screenshot_20170613-124314](https://user-images.githubusercontent.com/21035160/27079078-94603ffc-5036-11e7-8711-c38d35d409fb.png)

**Comment by DBozhinovski** [comment]
Not sure if appropriate here, use https://github.com/DBozhinovski/beerjs.mk

This repo should be used for general discussion related to Beer.js Skopje. :)

Thanks tho! :)
